// ─── ELITETC CLAUSE LIBRARY ─────────────────────────────────────────────────
// 38 NH-compliant clauses for real estate transaction addenda

export const CLAUSE_CATEGORIES = [
  { id: "all",       label: "All Clauses" },
  { id: "deadline",  label: "Deadline / Extension" },
  { id: "financial", label: "Financial" },
  { id: "inspection",label: "Inspection" },
  { id: "title",     label: "Title / Legal" },
  { id: "legal",     label: "Contingencies" },
  { id: "occupancy", label: "Occupancy" },
];

export const CLAUSE_LIBRARY = [

  // ─── DEADLINE EXTENSIONS ──────────────────────────────────────────────────
  {
    id: "ext_financial_commitment",
    name: "Financial Commitment Extension",
    category: "deadline",
    type: "extension",
    description: "Extends the mortgage/financial commitment deadline.",
    requiredInputs: [
      { key: "new_date",       label: "New Commitment Deadline",  type: "date"   },
      { key: "days_extended",  label: "Number of Days Extended",  type: "number" },
      { key: "reason",         label: "Reason for Extension",     type: "text"   },
    ],
    bodyTemplate: "The Financial Commitment deadline as set forth in the Purchase and Sales Agreement is hereby extended to [new_date], an extension of [days_extended] days. This extension is requested due to: [reason]. Buyer shall use diligent efforts to obtain financing within the extended period. All other terms remain unchanged.",
    tags: ["financing","extension","mortgage","commitment","deadline"],
    triggers: ["financing_deadline_approaching","financing_deadline_overdue"],
    version: 1, isActive: true,
  },
  {
    id: "ext_inspection_period",
    name: "Inspection Period Extension",
    category: "deadline",
    type: "extension",
    description: "Extends the inspection period deadline.",
    requiredInputs: [
      { key: "new_date",      label: "New Inspection Deadline", type: "date"   },
      { key: "days_extended", label: "Number of Days Extended", type: "number" },
      { key: "reason",        label: "Reason for Extension",    type: "text"   },
    ],
    bodyTemplate: "The Inspection Period deadline as set forth in the Purchase and Sales Agreement is hereby extended to [new_date], an extension of [days_extended] days, to allow additional time for: [reason]. Buyer's inspection rights shall continue through the extended deadline. All other terms remain unchanged.",
    tags: ["inspection","extension","deadline"],
    triggers: ["inspection_deadline_approaching","inspection_deadline_overdue"],
    version: 1, isActive: true,
  },
  {
    id: "ext_due_diligence",
    name: "Due Diligence Extension",
    category: "deadline",
    type: "extension",
    description: "Extends the due diligence period.",
    requiredInputs: [
      { key: "new_date",      label: "New Due Diligence Deadline", type: "date"   },
      { key: "days_extended", label: "Number of Days Extended",    type: "number" },
      { key: "reason",        label: "Reason for Extension",       type: "text"   },
    ],
    bodyTemplate: "The Due Diligence period as set forth in the Purchase and Sales Agreement is hereby extended to [new_date], an extension of [days_extended] days, to allow Buyer to: [reason]. All due diligence rights and obligations of both parties shall remain in full effect during the extended period. All other terms remain unchanged.",
    tags: ["due diligence","extension","deadline"],
    triggers: ["due_diligence_deadline_approaching","due_diligence_deadline_overdue"],
    version: 1, isActive: true,
  },
  {
    id: "ext_closing_date",
    name: "Closing Date Extension",
    category: "deadline",
    type: "extension",
    description: "Extends the closing / transfer of title date.",
    requiredInputs: [
      { key: "new_date",      label: "New Closing Date",          type: "date"   },
      { key: "days_extended", label: "Number of Days Extended",   type: "number" },
      { key: "time",          label: "Time of Closing",           type: "text"   },
      { key: "reason",        label: "Reason for Extension",      type: "text"   },
    ],
    bodyTemplate: "The Closing Date as set forth in the Purchase and Sales Agreement is hereby extended to [new_date] at [time], an extension of [days_extended] days. The reason for this extension is: [reason]. All rights, obligations, and conditions of the original Agreement remain in full force through the extended closing date. All other terms remain unchanged.",
    tags: ["closing","extension","deadline","title transfer"],
    triggers: ["closing_date_approaching","closing_date_overdue"],
    version: 1, isActive: true,
  },
  {
    id: "ext_appraisal_deadline",
    name: "Appraisal Deadline Extension",
    category: "deadline",
    type: "extension",
    description: "Extends the appraisal deadline.",
    requiredInputs: [
      { key: "new_date",      label: "New Appraisal Deadline", type: "date"   },
      { key: "days_extended", label: "Number of Days Extended", type: "number" },
      { key: "reason",        label: "Reason for Extension",   type: "text"   },
    ],
    bodyTemplate: "The Appraisal deadline as set forth in the Purchase and Sales Agreement is hereby extended to [new_date], an extension of [days_extended] days. This extension is necessitated by: [reason]. Buyer shall take all reasonable steps to complete the appraisal within the extended period. All other terms remain unchanged.",
    tags: ["appraisal","extension","deadline"],
    triggers: ["appraisal_deadline_approaching","appraisal_deadline_overdue"],
    version: 1, isActive: true,
  },
  {
    id: "ext_title_resolution",
    name: "Title Resolution Extension",
    category: "deadline",
    type: "extension",
    description: "Extends the title resolution period to cure title defects.",
    requiredInputs: [
      { key: "new_date",           label: "New Title Resolution Deadline", type: "date"   },
      { key: "days_extended",      label: "Number of Days Extended",       type: "number" },
      { key: "defect_description", label: "Description of Title Defect",   type: "text"   },
    ],
    bodyTemplate: "The Title Resolution period is hereby extended to [new_date], an extension of [days_extended] days, to allow Seller the opportunity to cure the following title defect(s): [defect_description]. If Seller is unable to deliver marketable title by [new_date], Buyer reserves all rights as set forth in the original Agreement. All other terms remain unchanged.",
    tags: ["title","extension","deadline","defect"],
    triggers: ["title_issue_flagged"],
    version: 1, isActive: true,
  },

  // ─── FINANCIAL ───────────────────────────────────────────────────────────
  {
    id: "seller_concession",
    name: "Seller Concession",
    category: "financial",
    type: "modification",
    description: "Seller contributes a specified amount toward Buyer's closing costs.",
    requiredInputs: [
      { key: "amount",  label: "Concession Amount ($)",                                   type: "currency" },
      { key: "purpose", label: "Purpose (e.g., closing costs, pre-paid items, repairs)",  type: "text"     },
    ],
    bodyTemplate: "Seller agrees to contribute [amount] toward Buyer's [purpose] at closing. This concession shall be reflected on the Closing Disclosure. The purchase price of the property remains unchanged. All other terms remain unchanged.",
    tags: ["concession","seller","closing costs","financial"],
    triggers: ["financial_issue_flagged","repair_credit_requested"],
    version: 1, isActive: true,
  },
  {
    id: "deposit_increase",
    name: "Deposit Increase",
    category: "financial",
    type: "modification",
    description: "Increases the earnest money deposit.",
    requiredInputs: [
      { key: "additional_amount", label: "Additional Deposit Amount ($)",  type: "currency" },
      { key: "new_amount",        label: "New Total Deposit Amount ($)",   type: "currency" },
      { key: "due_date",          label: "Additional Deposit Due Date",    type: "date"     },
      { key: "escrow_agent",      label: "Escrow Agent / Holder",          type: "text"     },
    ],
    bodyTemplate: "The earnest money deposit is hereby increased by [additional_amount], bringing the total deposit to [new_amount]. The additional deposit of [additional_amount] shall be delivered to [escrow_agent] on or before [due_date]. All other terms remain unchanged.",
    tags: ["deposit","earnest money","financial","increase"],
    triggers: ["deposit_modification"],
    version: 1, isActive: true,
  },
  {
    id: "deposit_reduction",
    name: "Deposit Reduction",
    category: "financial",
    type: "modification",
    description: "Reduces the earnest money deposit by mutual agreement.",
    requiredInputs: [
      { key: "reduction_amount", label: "Amount Reduced ($)",      type: "currency" },
      { key: "new_amount",       label: "New Deposit Amount ($)",  type: "currency" },
      { key: "reason",           label: "Reason for Reduction",    type: "text"     },
    ],
    bodyTemplate: "By mutual agreement, the earnest money deposit is hereby reduced by [reduction_amount] to a new total of [new_amount]. The reason for this reduction is: [reason]. The remaining deposit shall be held pursuant to the terms of the original Agreement. All other terms remain unchanged.",
    tags: ["deposit","earnest money","financial","reduction"],
    triggers: [],
    version: 1, isActive: true,
  },
  {
    id: "deposit_due_date_change",
    name: "Additional Deposit Due Date Change",
    category: "financial",
    type: "modification",
    description: "Changes the due date for an additional earnest money deposit.",
    requiredInputs: [
      { key: "deposit_amount", label: "Deposit Amount ($)",     type: "currency" },
      { key: "new_due_date",   label: "New Deposit Due Date",   type: "date"     },
      { key: "reason",         label: "Reason for Change",      type: "text"     },
    ],
    bodyTemplate: "The due date for the additional earnest money deposit of [deposit_amount] is hereby changed to [new_due_date]. This change is due to: [reason]. All other deposit terms remain as set forth in the original Agreement. All other terms remain unchanged.",
    tags: ["deposit","earnest money","financial","due date"],
    triggers: [],
    version: 1, isActive: true,
  },
  {
    id: "fuel_proration",
    name: "Fuel Proration Clause",
    category: "financial",
    type: "addendum",
    description: "Prorates fuel (oil, propane, kerosene) remaining in tanks at closing.",
    requiredInputs: [
      { key: "fuel_type",       label: "Fuel Type (e.g., heating oil, propane)", type: "text"     },
      { key: "price_per_unit",  label: "Agreed Price Per Gallon ($)",            type: "currency" },
      { key: "proration_method",label: "Proration Method (e.g., tank reading)",  type: "text"     },
    ],
    bodyTemplate: "Any [fuel_type] remaining in the storage tank(s) at the time of closing shall be prorated between Buyer and Seller based on [proration_method] at a price of [price_per_unit] per gallon. Seller shall provide documentation of the current tank level to the closing attorney no later than 48 hours prior to closing. The prorated amount shall be credited at closing. All other terms remain unchanged.",
    tags: ["fuel","proration","oil","propane","closing","financial"],
    triggers: ["fuel_present","residential_property"],
    version: 1, isActive: true,
  },
  {
    id: "buyer_credit_repairs",
    name: "Buyer Credit in Lieu of Repairs",
    category: "financial",
    type: "modification",
    description: "Seller provides a closing credit instead of making repairs.",
    requiredInputs: [
      { key: "credit_amount",      label: "Credit Amount ($)",                    type: "currency" },
      { key: "repair_description", label: "Description of Repairs / Issues",      type: "text"     },
    ],
    bodyTemplate: "In lieu of Seller performing the following repairs: [repair_description], Seller agrees to provide Buyer a credit of [credit_amount] at closing, to be applied toward Buyer's closing costs or as a purchase price adjustment as determined by the parties' lender and closing attorney. Buyer accepts the property in its current condition as it relates to the described repairs. All other terms remain unchanged.",
    tags: ["credit","repairs","financial","inspection","closing"],
    triggers: ["inspection_issues_flagged","repair_request"],
    version: 1, isActive: true,
  },

  // ─── INSPECTION ──────────────────────────────────────────────────────────
  {
    id: "general_inspection_contingency",
    name: "General Inspection Contingency",
    category: "inspection",
    type: "contingency",
    description: "Makes the sale contingent upon a satisfactory general home inspection.",
    requiredInputs: [
      { key: "inspection_deadline", label: "Inspection Deadline",         type: "date" },
      { key: "inspector_name",      label: "Inspector Name / Company",    type: "text" },
    ],
    bodyTemplate: "This Agreement is contingent upon Buyer obtaining, at Buyer's expense, a satisfactory general home inspection by [inspector_name] on or before [inspection_deadline]. If the inspection reveals defects that Buyer deems unsatisfactory and the parties cannot reach a mutually agreeable resolution, Buyer may withdraw and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["inspection","contingency","general"],
    triggers: ["inspection_contingency"],
    version: 1, isActive: true,
  },
  {
    id: "radon_contingency",
    name: "Radon Contingency",
    category: "inspection",
    type: "contingency",
    description: "Sale contingent upon acceptable radon levels per NH/EPA standards.",
    requiredInputs: [
      { key: "test_deadline",    label: "Radon Test Deadline",                type: "date"   },
      { key: "acceptable_level", label: "Acceptable Radon Level (pCi/L)",    type: "number" },
    ],
    bodyTemplate: "This Agreement is contingent upon a radon test of the property revealing levels at or below [acceptable_level] pCi/L (U.S. EPA action level is 4.0 pCi/L), to be completed on or before [test_deadline]. If levels exceed the threshold, Seller may install a NH-approved mitigation system at Seller's expense, or the parties may negotiate an alternative. If no resolution is reached, Buyer may withdraw and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["radon","inspection","contingency","NH","environmental"],
    triggers: ["radon_test"],
    version: 1, isActive: true,
  },
  {
    id: "water_quality_contingency",
    name: "Water Quality Contingency",
    category: "inspection",
    type: "contingency",
    description: "Sale contingent upon acceptable water quality test results.",
    requiredInputs: [
      { key: "test_deadline",    label: "Water Test Deadline",                                       type: "date" },
      { key: "water_source",     label: "Water Source (e.g., private well, public municipal)",      type: "text" },
      { key: "test_parameters",  label: "Test Parameters (e.g., bacteria, arsenic, nitrates, PFAS)",type: "text" },
    ],
    bodyTemplate: "This Agreement is contingent upon water quality test results from the [water_source] meeting applicable NH DES standards for: [test_parameters], to be completed on or before [test_deadline]. If results exceed NH DES standards, Seller may elect to install an approved treatment system or negotiate an alternative remedy. If no resolution is reached, Buyer may withdraw and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["water","well","quality","contingency","NH DES","inspection"],
    triggers: ["private_well","water_test"],
    version: 1, isActive: true,
  },
  {
    id: "septic_inspection_contingency",
    name: "Septic System Inspection Contingency",
    category: "inspection",
    type: "contingency",
    description: "Sale contingent upon a satisfactory septic system inspection.",
    requiredInputs: [
      { key: "test_deadline",   label: "Septic Inspection Deadline",          type: "date" },
      { key: "inspector_name",  label: "Licensed Inspector Name / Company",   type: "text" },
    ],
    bodyTemplate: "This Agreement is contingent upon a septic system inspection by licensed inspector [inspector_name], to be completed on or before [test_deadline]. The inspection shall include a visual evaluation and, if applicable, a load or dye test as required by NH law. If the system is found to be non-conforming or in need of material repairs, the parties shall negotiate a resolution. If no resolution is reached, Buyer may withdraw and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["septic","inspection","contingency","NH","well and septic"],
    triggers: ["septic_system"],
    version: 1, isActive: true,
  },
  {
    id: "repair_request",
    name: "Repair Request Clause",
    category: "inspection",
    type: "modification",
    description: "Formal repair request following inspection findings.",
    requiredInputs: [
      { key: "repair_items",         label: "Itemized Repair Requests",                              type: "text" },
      { key: "completion_deadline",  label: "Repair Completion Deadline",                            type: "date" },
      { key: "repair_standard",      label: "Completion Standard (e.g., licensed contractor, receipt required)", type: "text" },
    ],
    bodyTemplate: "As a result of the property inspection, Buyer hereby requests that Seller complete the following repairs prior to closing, on or before [completion_deadline]: [repair_items]. All repairs shall be performed by [repair_standard]. Documentation of completed repairs shall be provided to Buyer no later than 48 hours prior to closing. Buyer reserves the right to a final walk-through to verify completion. All other terms remain unchanged.",
    tags: ["repair","inspection","request","modification"],
    triggers: ["inspection_issues_flagged"],
    version: 1, isActive: true,
  },
  {
    id: "repair_escrow_holdback",
    name: "Repair Escrow Holdback",
    category: "inspection",
    type: "modification",
    description: "Funds held in escrow post-closing to ensure agreed repairs are completed.",
    requiredInputs: [
      { key: "holdback_amount",    label: "Escrow Holdback Amount ($)",     type: "currency" },
      { key: "repair_description", label: "Description of Required Repairs", type: "text"    },
      { key: "completion_deadline",label: "Repair Completion Deadline",      type: "date"    },
      { key: "escrow_agent",       label: "Escrow Agent",                    type: "text"    },
    ],
    bodyTemplate: "The sum of [holdback_amount] shall be withheld from Seller's proceeds at closing and held in escrow by [escrow_agent] to ensure completion of the following repairs: [repair_description]. Funds shall be released to Seller upon documented completion on or before [completion_deadline]. If repairs are not completed by [completion_deadline], Buyer may use the escrowed funds to complete said repairs. All other terms remain unchanged.",
    tags: ["escrow","holdback","repair","inspection","closing"],
    triggers: ["repair_agreed","post_closing_repairs"],
    version: 1, isActive: true,
  },
  {
    id: "as_is_acceptance",
    name: "As-Is Acceptance",
    category: "inspection",
    type: "modification",
    description: "Buyer accepts the property in its current condition.",
    requiredInputs: [
      { key: "inspection_date", label: "Inspection Completion Date",           type: "date" },
      { key: "known_defects",   label: "Known Defects Acknowledged (if any)",  type: "text" },
    ],
    bodyTemplate: "Following the property inspection completed on [inspection_date], Buyer agrees to accept the property in its present as-is condition, including the following known defects: [known_defects]. Seller shall have no obligation to make additional repairs or concessions arising from the inspection. Buyer acknowledges this acceptance is made with full knowledge of the property's condition. All other terms remain unchanged.",
    tags: ["as-is","inspection","acceptance","waiver"],
    triggers: [],
    version: 1, isActive: true,
  },
  {
    id: "inspection_contingency_removal",
    name: "Inspection Contingency Removal",
    category: "inspection",
    type: "modification",
    description: "Buyer formally waives and removes the inspection contingency.",
    requiredInputs: [
      { key: "removal_date", label: "Date of Removal", type: "date" },
      { key: "reason",       label: "Reason for Removal", type: "text" },
    ],
    bodyTemplate: "Effective [removal_date], Buyer hereby waives and removes the inspection contingency as set forth in the Purchase and Sales Agreement. Buyer acknowledges acceptance of the property in its current condition. [reason]. All other terms remain unchanged.",
    tags: ["inspection","contingency","removal","waiver"],
    triggers: [],
    version: 1, isActive: true,
  },

  // ─── TITLE / LEGAL ───────────────────────────────────────────────────────
  {
    id: "marketable_title_cure",
    name: "Marketable Title Cure Period",
    category: "title",
    type: "modification",
    description: "Grants Seller additional time and a cost cap to cure title defects.",
    requiredInputs: [
      { key: "defect_description", label: "Title Defect Description",           type: "text"     },
      { key: "cure_deadline",      label: "Title Cure Deadline",                type: "date"     },
      { key: "cure_cost_limit",    label: "Maximum Seller Cure Cost ($)",        type: "currency" },
    ],
    bodyTemplate: "Seller shall have until [cure_deadline] to cure the following title defect(s) at a cost not to exceed [cure_cost_limit]: [defect_description]. If Seller is unable to deliver marketable title by [cure_deadline], Buyer may, at Buyer's sole option: (a) accept title in its current condition, (b) extend the cure period by mutual written agreement, or (c) terminate this Agreement and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["title","cure","defect","marketable","legal"],
    triggers: ["title_issue_flagged"],
    version: 1, isActive: true,
  },
  {
    id: "attorney_review_contingency",
    name: "Attorney Review Contingency",
    category: "title",
    type: "contingency",
    description: "Sale contingent upon satisfactory attorney review of the agreement.",
    requiredInputs: [
      { key: "review_deadline", label: "Attorney Review Deadline", type: "date" },
      { key: "attorney_name",   label: "Attorney Name / Firm",     type: "text" },
    ],
    bodyTemplate: "This Agreement is contingent upon review and approval by [attorney_name] on or before [review_deadline]. If the reviewing attorney raises objections that cannot be resolved by mutual written agreement within 5 business days, the objecting party may withdraw from this Agreement and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["attorney","review","contingency","legal"],
    triggers: ["attorney_review"],
    version: 1, isActive: true,
  },
  {
    id: "property_survey_contingency",
    name: "Property Survey Contingency",
    category: "title",
    type: "contingency",
    description: "Sale contingent upon a satisfactory property survey.",
    requiredInputs: [
      { key: "survey_deadline", label: "Survey Completion Deadline",                    type: "date" },
      { key: "survey_company",  label: "Licensed Surveyor / Company",                   type: "text" },
      { key: "survey_type",     label: "Survey Type (e.g., boundary, ALTA/NSPS)",       type: "text" },
    ],
    bodyTemplate: "This Agreement is contingent upon Buyer obtaining a satisfactory [survey_type] survey by [survey_company] on or before [survey_deadline]. If the survey reveals boundary discrepancies, encroachments, or issues material to Buyer's intended use that cannot be resolved by mutual agreement, Buyer may withdraw and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["survey","boundary","title","contingency"],
    triggers: ["survey_required"],
    version: 1, isActive: true,
  },
  {
    id: "easement_encumbrance_review",
    name: "Easement and Encumbrance Review",
    category: "title",
    type: "contingency",
    description: "Buyer reviews all easements and encumbrances affecting the property.",
    requiredInputs: [
      { key: "review_deadline",      label: "Review Deadline",                   type: "date" },
      { key: "easement_description", label: "Known Easement(s) / Encumbrance(s)",type: "text" },
    ],
    bodyTemplate: "Buyer shall have until [review_deadline] to review all easements, restrictions, covenants, and encumbrances of record affecting the property, including but not limited to: [easement_description]. If Buyer determines any encumbrance materially impairs Buyer's intended use, Buyer shall notify Seller in writing and the parties shall negotiate in good faith. If no resolution is reached, Buyer may withdraw and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["easement","encumbrance","title","review","legal"],
    triggers: ["title_issue_flagged"],
    version: 1, isActive: true,
  },

  // ─── CONTINGENCIES ────────────────────────────────────────────────────────
  {
    id: "appraisal_contingency",
    name: "Appraisal Contingency",
    category: "legal",
    type: "contingency",
    description: "Sale contingent upon property appraising at or above the purchase price.",
    requiredInputs: [
      { key: "purchase_price",    label: "Purchase Price ($)",    type: "currency" },
      { key: "appraisal_deadline",label: "Appraisal Deadline",   type: "date"     },
    ],
    bodyTemplate: "This Agreement is contingent upon the property appraising at a value equal to or greater than [purchase_price], as determined by a licensed appraiser selected by Buyer's lender, on or before [appraisal_deadline]. If the appraised value is less than the purchase price and the parties cannot reach a mutually agreeable resolution, Buyer may withdraw and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["appraisal","contingency","financing","value"],
    triggers: ["appraisal_deadline_approaching","appraisal_missing"],
    version: 1, isActive: true,
  },
  {
    id: "sale_of_buyers_property",
    name: "Sale of Buyer's Property Contingency",
    category: "legal",
    type: "contingency",
    description: "Sale contingent upon Buyer successfully selling their current property.",
    requiredInputs: [
      { key: "buyers_property_address", label: "Buyer's Property Address",  type: "text" },
      { key: "sale_deadline",           label: "Sale Deadline",             type: "date" },
    ],
    bodyTemplate: "This Agreement is contingent upon the sale and closing of Buyer's property located at [buyers_property_address] on or before [sale_deadline]. Buyer shall provide Seller with written notice of the sale status within 5 business days. If Buyer's property has not sold by [sale_deadline], Seller may, at Seller's sole option, cancel this Agreement, and all earnest money shall be returned to Buyer. All other terms remain unchanged.",
    tags: ["sale contingency","buyer property","contingency"],
    triggers: ["buyer_selling_property"],
    version: 1, isActive: true,
  },
  {
    id: "buyer_home_under_contract",
    name: "Buyer's Home Under Contract Contingency",
    category: "legal",
    type: "contingency",
    description: "Buyer's current property is under contract; sets conditions and notice requirements.",
    requiredInputs: [
      { key: "buyers_property_address", label: "Buyer's Current Property Address",    type: "text"   },
      { key: "buyers_closing_date",     label: "Buyer's Expected Closing Date",       type: "date"   },
      { key: "notice_period",           label: "Required Notice Period (days)",       type: "number" },
    ],
    bodyTemplate: "Buyer represents that their current property located at [buyers_property_address] is under a Purchase and Sales Agreement with an expected closing date of [buyers_closing_date]. This Agreement is contingent upon the closing of Buyer's current property. Buyer shall provide Seller with [notice_period] days written notice if Buyer's closing is delayed or cancelled. If Buyer's closing fails, the parties shall negotiate in good faith or either party may terminate. All other terms remain unchanged.",
    tags: ["sale contingency","buyer property","under contract","contingency"],
    triggers: ["buyer_selling_property"],
    version: 1, isActive: true,
  },
  {
    id: "board_approval_contingency",
    name: "Board Approval Contingency (HOA/Condo)",
    category: "legal",
    type: "contingency",
    description: "Sale contingent upon approval by the HOA or condo association board.",
    requiredInputs: [
      { key: "association_name",  label: "Association Name",   type: "text" },
      { key: "approval_deadline", label: "Approval Deadline",  type: "date" },
    ],
    bodyTemplate: "This Agreement is contingent upon approval by the Board of Directors or governing body of [association_name] on or before [approval_deadline]. Seller shall submit all required application materials within 5 business days of execution of this Agreement. If approval is denied or not obtained by [approval_deadline], Buyer may withdraw and receive a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["HOA","condo","board approval","contingency","association"],
    triggers: ["condo_property","hoa_required"],
    version: 1, isActive: true,
  },
  {
    id: "insurance_contingency",
    name: "Insurance Availability Contingency",
    category: "legal",
    type: "contingency",
    description: "Sale contingent upon Buyer obtaining satisfactory property insurance.",
    requiredInputs: [
      { key: "insurance_deadline", label: "Insurance Binding Deadline",  type: "date" },
      { key: "coverage_type",      label: "Required Coverage Type",      type: "text" },
    ],
    bodyTemplate: "This Agreement is contingent upon Buyer obtaining a binder for [coverage_type] insurance coverage at a premium and with terms acceptable to Buyer on or before [insurance_deadline]. If Buyer is unable to obtain satisfactory coverage, Buyer may notify Seller in writing and withdraw from this Agreement, receiving a full refund of the earnest money deposit. All other terms remain unchanged.",
    tags: ["insurance","contingency","homeowners","flood"],
    triggers: ["insurance_required"],
    version: 1, isActive: true,
  },

  // ─── OCCUPANCY ────────────────────────────────────────────────────────────
  {
    id: "post_closing_occupancy",
    name: "Post-Closing Occupancy Agreement",
    category: "occupancy",
    type: "addendum",
    description: "Seller remains in the property for a defined period after closing.",
    requiredInputs: [
      { key: "occupancy_end_date", label: "Occupancy End Date",           type: "date"     },
      { key: "daily_rate",         label: "Daily Occupancy Rate ($)",     type: "currency" },
      { key: "security_deposit",   label: "Security Deposit Amount ($)",  type: "currency" },
    ],
    bodyTemplate: "Following the closing and transfer of title, Seller shall be permitted to remain in occupancy of the property until [occupancy_end_date] at a daily rate of [daily_rate], payable to Buyer at closing. Seller shall deposit [security_deposit] as a security deposit at closing, to be returned within 5 business days of vacating, less amounts owed for damages or unpaid fees. Seller shall vacate and deliver the property in broom-clean condition by [occupancy_end_date]. All other terms remain unchanged.",
    tags: ["occupancy","post-closing","seller","rent-back"],
    triggers: ["post_closing_occupancy_requested"],
    version: 1, isActive: true,
  },
  {
    id: "pre_closing_occupancy",
    name: "Pre-Closing Occupancy Agreement",
    category: "occupancy",
    type: "addendum",
    description: "Buyer is permitted to occupy the property before closing.",
    requiredInputs: [
      { key: "occupancy_start_date", label: "Early Occupancy Start Date",    type: "date"     },
      { key: "daily_rate",           label: "Daily Occupancy Rate ($)",      type: "currency" },
      { key: "security_deposit",     label: "Security Deposit Amount ($)",   type: "currency" },
    ],
    bodyTemplate: "Seller hereby grants Buyer permission to occupy the property beginning [occupancy_start_date] through the date of closing at a daily rate of [daily_rate]. Buyer shall pay a security deposit of [security_deposit] prior to taking possession. Buyer acknowledges this arrangement is a license to occupy only and not a tenancy. In the event the transaction does not close, Buyer shall vacate within 48 hours of written notice. All other terms remain unchanged.",
    tags: ["occupancy","pre-closing","buyer","early possession"],
    triggers: ["pre_closing_occupancy_requested"],
    version: 1, isActive: true,
  },
  {
    id: "hold_harmless",
    name: "Hold Harmless Agreement",
    category: "occupancy",
    type: "addendum",
    description: "One party indemnifies and holds harmless the other during an occupancy period.",
    requiredInputs: [
      { key: "indemnifying_party", label: "Indemnifying Party (Buyer or Seller)", type: "text" },
      { key: "indemnified_party",  label: "Indemnified Party",                    type: "text" },
      { key: "period_start",       label: "Indemnification Period Start",         type: "date" },
      { key: "period_end",         label: "Indemnification Period End",           type: "date" },
    ],
    bodyTemplate: "[indemnifying_party] hereby agrees to indemnify, defend, and hold harmless [indemnified_party] from and against any and all claims, losses, damages, liabilities, and expenses arising out of or relating to [indemnifying_party]'s occupancy of the property during the period from [period_start] through [period_end], including but not limited to personal injury, property damage, and third-party claims. All other terms remain unchanged.",
    tags: ["hold harmless","indemnification","occupancy","legal"],
    triggers: ["occupancy_agreement"],
    version: 1, isActive: true,
  },
  {
    id: "rent_back_agreement",
    name: "Rent-Back Agreement",
    category: "occupancy",
    type: "addendum",
    description: "Seller rents the property from Buyer post-closing for a defined period.",
    requiredInputs: [
      { key: "rent_start_date",  label: "Rent-Back Start Date (Closing Date)", type: "date"     },
      { key: "rent_end_date",    label: "Rent-Back End Date",                  type: "date"     },
      { key: "monthly_rent",     label: "Monthly Rent ($)",                    type: "currency" },
      { key: "security_deposit", label: "Security Deposit ($)",                type: "currency" },
    ],
    bodyTemplate: "Following closing on [rent_start_date], Seller shall rent the property from Buyer at [monthly_rent] per month through [rent_end_date], at which time Seller shall vacate. A security deposit of [security_deposit] shall be collected at closing and returned within 5 business days of vacating, less amounts owed. Seller shall maintain the property in good condition, carry renter's insurance, and be responsible for all utilities during the rent-back period. All other terms remain unchanged.",
    tags: ["rent-back","occupancy","seller","post-closing"],
    triggers: ["post_closing_occupancy_requested"],
    version: 1, isActive: true,
  },

  // ─── MISCELLANEOUS ────────────────────────────────────────────────────────
  {
    id: "personal_property_included",
    name: "Personal Property Included",
    category: "legal",
    type: "modification",
    description: "Specifies personal property items included in the sale.",
    requiredInputs: [
      { key: "property_list", label: "List of Personal Property Items Included", type: "text" },
    ],
    bodyTemplate: "The following personal property items are included in the purchase price and shall convey with the real property at closing: [property_list]. Seller warrants that all listed personal property is owned free and clear of any liens and shall be in working condition at the time of closing. All other terms remain unchanged.",
    tags: ["personal property","included","fixtures","sale"],
    triggers: [],
    version: 1, isActive: true,
  },
  {
    id: "personal_property_excluded",
    name: "Personal Property Excluded",
    category: "legal",
    type: "modification",
    description: "Specifies items excluded from the sale.",
    requiredInputs: [
      { key: "excluded_items", label: "List of Excluded Items", type: "text" },
    ],
    bodyTemplate: "Notwithstanding any language in the Purchase and Sales Agreement, the following items are excluded from the sale and shall be removed by Seller prior to closing: [excluded_items]. Seller shall repair any damage caused by such removal to Buyer's reasonable satisfaction prior to closing. All other terms remain unchanged.",
    tags: ["personal property","excluded","fixtures","removal"],
    triggers: [],
    version: 1, isActive: true,
  },
  {
    id: "delayed_showings",
    name: "Delayed Showings Clause",
    category: "legal",
    type: "modification",
    description: "Delays property showings until a specified date.",
    requiredInputs: [
      { key: "showing_start_date", label: "Showings Commence Date", type: "date" },
      { key: "reason",             label: "Reason for Delay",       type: "text" },
    ],
    bodyTemplate: "By mutual agreement, property showings shall not commence until [showing_start_date]. The reason for the delayed showing period is: [reason]. All other rights and obligations under the Agreement remain in full force and effect during this period. All other terms remain unchanged.",
    tags: ["showings","delayed","listing","access"],
    triggers: [],
    version: 1, isActive: true,
  },
  {
    id: "confidentiality_clause",
    name: "Confidentiality Clause",
    category: "legal",
    type: "addendum",
    description: "Requires both parties to keep specified terms confidential.",
    requiredInputs: [
      { key: "confidential_items", label: "Confidential Terms (e.g., purchase price, concessions)",       type: "text" },
      { key: "exceptions",         label: "Permitted Exceptions (e.g., lenders, attorneys, accountants)", type: "text" },
    ],
    bodyTemplate: "The parties agree to keep the following terms of this Agreement confidential: [confidential_items]. Neither party shall disclose said information to any third party except as required by law or as necessary to disclose to: [exceptions]. This obligation of confidentiality shall survive the closing of this transaction. All other terms remain unchanged.",
    tags: ["confidentiality","privacy","NDA","legal"],
    triggers: [],
    version: 1, isActive: true,
  },
  {
    id: "entire_agreement",
    name: "Entire Agreement Clause",
    category: "legal",
    type: "addendum",
    description: "Confirms this addendum and the original agreement constitute the entire understanding.",
    requiredInputs: [
      { key: "addendum_date", label: "Addendum Date", type: "date" },
    ],
    bodyTemplate: "This Addendum, dated [addendum_date], together with the original Purchase and Sales Agreement and all prior addenda, constitutes the entire agreement between the parties regarding the purchase and sale of the property. No oral representations or modifications shall be binding unless made in writing and signed by all parties. All other terms remain unchanged.",
    tags: ["entire agreement","legal","merger clause"],
    triggers: [],
    version: 1, isActive: true,
  },
];