import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

const BID = "69af731d6de2faa420d7aace";

const TRANSACTIONS = [
    {
        brokerage_id: BID,
        address: "42 Birchwood Lane, Concord, NH 03301",
        buyer: "James & Linda Harrington",
        seller: "Robert Keene",
        buyers: ["James Harrington", "Linda Harrington"],
        sellers: ["Robert Keene"],
        buyers_agent_name: "Sarah Mitchell",
        sellers_agent_name: "Tom Bellows",
        buyer_brokerage: "Granite Peak Realty",
        seller_brokerage: "Bellows & Associates",
        agent: "Sarah Mitchell",
        agent_email: "nhcazateam@gmail.com",
        closing_title_company: "Concord Title Group",
        mls_number: "MLS-4421890",
        commission: "2.5",
        client_email: "james.harrington@email.com",
        client_phone: "603-555-0201",
        is_cash_transaction: false,
        contract_date: "2026-02-15",
        closing_date: "2026-03-28",
        transaction_type: "buyer",
        phase: 8,
        phases_completed: [3, 5, 7],
        status: "active",
        pipeline_stage: "Clear to Close",
        health_score: 85,
        risk_level: "on_track",
        inspection_deadline: "2026-02-22",
        appraisal_deadline: "2026-03-05",
        financing_deadline: "2026-03-12",
        due_diligence_deadline: "2026-02-25",
        earnest_money_deadline: "2026-02-18"
    },
    {
        brokerage_id: BID,
        address: "7 Maple Ridge Road, Manchester, NH 03104",
        buyer: "Carlos & Maria Delgado",
        seller: "Patricia Simmons",
        buyers: ["Carlos Delgado", "Maria Delgado"],
        sellers: ["Patricia Simmons"],
        buyers_agent_name: "Derek Foss",
        sellers_agent_name: "Sarah Mitchell",
        buyer_brokerage: "Premier NH Homes",
        seller_brokerage: "Granite Peak Realty",
        agent: "Sarah Mitchell",
        agent_email: "nhcazateam@gmail.com",
        closing_title_company: "Manchester Title & Escrow",
        mls_number: "MLS-4398701",
        commission: "3.0",
        client_email: "patricia.simmons@email.com",
        client_phone: "603-555-0342",
        is_cash_transaction: false,
        contract_date: "2026-02-20",
        closing_date: "2026-04-04",
        transaction_type: "seller",
        phase: 7,
        phases_completed: [3, 5],
        status: "active",
        pipeline_stage: "Financing Contingency",
        health_score: 62,
        risk_level: "watch",
        inspection_deadline: "2026-02-27",
        appraisal_deadline: "2026-03-10",
        financing_deadline: "2026-03-17",
        due_diligence_deadline: "2026-03-01",
        earnest_money_deadline: "2026-02-23"
    },
    {
        brokerage_id: BID,
        address: "305 Lakeside Drive, Laconia, NH 03246",
        buyer: "Thomas & Rebecca Nguyen",
        seller: "Westfield Properties LLC",
        buyers: ["Thomas Nguyen", "Rebecca Nguyen"],
        sellers: ["Westfield Properties LLC"],
        buyers_agent_name: "Sarah Mitchell",
        sellers_agent_name: "Alan Wright",
        buyer_brokerage: "Granite Peak Realty",
        seller_brokerage: "Wright Realty Group",
        agent: "Sarah Mitchell",
        agent_email: "nhcazateam@gmail.com",
        closing_title_company: "Lakes Region Title",
        mls_number: "MLS-4412003",
        commission: "2.5",
        client_email: "thomas.nguyen@email.com",
        client_phone: "603-555-0489",
        is_cash_transaction: true,
        contract_date: "2026-03-01",
        closing_date: "2026-03-21",
        transaction_type: "buyer",
        phase: 10,
        phases_completed: [3, 5, 7, 8, 9],
        status: "active",
        pipeline_stage: "Closing Prep",
        health_score: 45,
        risk_level: "at_risk",
        inspection_deadline: "2026-03-08",
        due_diligence_deadline: "2026-03-10",
        earnest_money_deadline: "2026-03-04",
        ctc_target: "2026-03-19"
    },
    {
        brokerage_id: BID,
        address: "18 Elm Street, Nashua, NH 03060",
        buyer: "Jennifer Okafor",
        seller: "Daniel & Cynthia Park",
        buyers: ["Jennifer Okafor"],
        sellers: ["Daniel Park", "Cynthia Park"],
        buyers_agent_name: "Lisa Tran",
        sellers_agent_name: "Sarah Mitchell",
        buyer_brokerage: "Nashua Home Solutions",
        seller_brokerage: "Granite Peak Realty",
        agent: "Sarah Mitchell",
        agent_email: "nhcazateam@gmail.com",
        closing_title_company: "Nashua Title Works",
        mls_number: "MLS-4401556",
        commission: "3.0",
        client_email: "daniel.park@email.com",
        client_phone: "603-555-0612",
        is_cash_transaction: false,
        contract_date: "2026-01-10",
        closing_date: "2026-02-28",
        transaction_type: "seller",
        phase: 12,
        phases_completed: [3, 5, 7, 8, 9, 10, 11],
        status: "closed",
        pipeline_stage: "Closed",
        health_score: 100,
        risk_level: "on_track",
        inspection_deadline: "2026-01-17",
        appraisal_deadline: "2026-01-28",
        financing_deadline: "2026-02-05",
        due_diligence_deadline: "2026-01-20",
        earnest_money_deadline: "2026-01-13"
    },
    {
        brokerage_id: BID,
        address: "91 Pine Hollow Court, Dover, NH 03820",
        buyer: "Marcus & Angela Webb",
        seller: "Sunrise Development Corp",
        buyers: ["Marcus Webb", "Angela Webb"],
        sellers: ["Sunrise Development Corp"],
        buyers_agent_name: "Sarah Mitchell",
        sellers_agent_name: "Greg Fontaine",
        buyer_brokerage: "Granite Peak Realty",
        seller_brokerage: "Seacoast Premier Realty",
        agent: "Sarah Mitchell",
        agent_email: "nhcazateam@gmail.com",
        closing_title_company: "Seacoast Closing Services",
        mls_number: "MLS-4430087",
        commission: "2.75",
        client_email: "marcus.webb@email.com",
        client_phone: "603-555-0778",
        is_cash_transaction: false,
        contract_date: "2026-03-05",
        closing_date: "2026-04-18",
        transaction_type: "buyer",
        phase: 5,
        phases_completed: [3],
        status: "active",
        pipeline_stage: "Inspection Period",
        health_score: 90,
        risk_level: "on_track",
        inspection_deadline: "2026-03-12",
        appraisal_deadline: "2026-03-26",
        financing_deadline: "2026-04-02",
        due_diligence_deadline: "2026-03-15",
        earnest_money_deadline: "2026-03-08"
    },
    {
        brokerage_id: BID,
        address: "224 Granite Falls Blvd, Keene, NH 03431",
        buyer: "Steven & Holly Bradford",
        seller: "Eleanor Marsh",
        buyers: ["Steven Bradford", "Holly Bradford"],
        sellers: ["Eleanor Marsh"],
        buyers_agent_name: "Sarah Mitchell",
        sellers_agent_name: "Diane Cooks",
        buyer_brokerage: "Granite Peak Realty",
        seller_brokerage: "Monadnock Realty",
        agent: "Sarah Mitchell",
        agent_email: "nhcazateam@gmail.com",
        closing_title_company: "Keene Valley Title",
        mls_number: "MLS-4418822",
        commission: "2.5",
        client_email: "steven.bradford@email.com",
        client_phone: "603-555-0901",
        is_cash_transaction: false,
        contract_date: "2026-02-01",
        closing_date: "2026-03-15",
        transaction_type: "dual",
        phase: 9,
        phases_completed: [3, 5, 7, 8],
        status: "active",
        pipeline_stage: "Appraisal",
        health_score: 71,
        risk_level: "watch",
        inspection_deadline: "2026-02-08",
        appraisal_deadline: "2026-02-20",
        financing_deadline: "2026-02-28",
        due_diligence_deadline: "2026-02-11",
        earnest_money_deadline: "2026-02-04",
        ctc_target: "2026-03-13"
    }
];

Deno.serve(async (req) => {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) {
        return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const created = [];
    for (const t of TRANSACTIONS) {
        const tx = await base44.asServiceRole.entities.Transaction.create(t);
        created.push(tx.id);
    }

    return Response.json({
        success: true,
        transactions_created: created.length,
        ids: created
    });
});